name: build4all_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2            # pinned by Flutter SDK, keep this
  cupertino_icons: ^1.0.8  # keep ONLY one entry

  # Core
  dio: ^5.7.0
  go_router: ^14.2.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  collection: ^1.18.0

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # required for gen-l10n
