name: build4all_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.10.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  country_picker: ^2.0.25
  phone_numbers_parser: ^8.0.0
  email_validator: ^2.1.0
  flutter_multi_formatter: ^2.12.10
  intl_phone_field: ^3.2.0
  dio: ^5.7.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.5
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  path: ^1.9.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_typeahead: ^5.2.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  geocoding: ^2.2.2
  pdf: ^3.11.0
  printing: ^5.11.1
  flutter_slidable: ^3.1.0
  auto_size_text: ^3.0.0
  material_symbols_icons: ^4.2719.1
  path_provider: ^2.1.2
  excel: ^4.0.2
  open_filex: ^4.4.0
  web_socket_channel: ^3.0.1
  ionicons: ^0.2.2
  flutter_stripe: ^10.0.0
  connectivity_plus: ^6.0.5
  go_router: ^14.2.1
  file_picker: ^8.1.2

  # Core
  collection: ^1.18.0

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/config/hostIp.json
